# Generated by Django 4.0.3 on 2022-03-20 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_bio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
    ]
