# Generated by Django 4.0.3 on 2022-03-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
