# Generated by Django 4.0.3 on 2022-03-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_resume', '0002_entry_entry_id_journal_journal_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='journal',
            name='list_label',
            field=models.CharField(default='list', max_length=12),
            preserve_default=False,
        ),
    ]
