# Generated by Django 4.0.3 on 2022-03-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_resume', '0003_alter_entry_options_journal_list_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='end',
            field=models.DateField(blank=True, default='2022-03-16'),
        ),
        migrations.AddField(
            model_name='entry',
            name='start',
            field=models.DateField(blank=True, default='2022-03-16'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='list_label',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
