# Generated by Django 4.0.3 on 2022-03-17 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_resume', '0004_entry_blurb_entry_end_entry_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start',
            field=models.DateField(blank=True),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.IntegerField(blank=True)),
                ('label', models.CharField(blank=True, max_length=24)),
                ('employer', models.CharField(blank=True, max_length=48)),
                ('street', models.CharField(blank=True, max_length=48)),
                ('city', models.CharField(blank=True, max_length=24)),
                ('state', models.CharField(blank=True, max_length=24)),
                ('start', models.DateField(default='2022-03-16')),
                ('end', models.DateField(default='2022-03-16')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_resume.entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='positions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_positions', to='_resume.position'),
        ),
    ]
