# Generated by Django 4.0.3 on 2022-03-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_resume', '0005_alter_entry_end_alter_entry_start_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='positions',
        ),
        migrations.AddField(
            model_name='entry',
            name='positions',
            field=models.ManyToManyField(null=True, related_name='entry_positions', to='_resume.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='label',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
