# Generated by Django 4.0.3 on 2022-03-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_resume', '0007_certificate_remove_entry_journal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_id',
        ),
    ]
