# Generated by Django 4.0.3 on 2022-03-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_resume', '0008_remove_entry_entry_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='progams',
            new_name='programs',
        ),
        migrations.AlterField(
            model_name='entry',
            name='end',
            field=models.DateField(blank=True, default='2022-03-16', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='label',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start',
            field=models.DateField(blank=True, default='2022-03-16', null=True),
        ),
    ]
