# Generated by Django 4.0.3 on 2022-03-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=24)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=48)),
                ('responsibilities', models.ManyToManyField(blank=True, related_name='position_responsibilities', to='_work.responsibility')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=48)),
                ('start', models.DateField(blank=True)),
                ('end', models.DateField(blank=True)),
                ('city', models.CharField(max_length=24)),
                ('state', models.CharField(max_length=24)),
                ('positions', models.ManyToManyField(blank=True, related_name='entry_positions', to='_work.position')),
            ],
        ),
    ]
