# Generated by Django 4.0.3 on 2022-03-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='responsibility',
            options={'verbose_name_plural': 'Responsibilities'},
        ),
    ]
