# Generated by Django 4.0.3 on 2022-03-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_work', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responsibility',
            new_name='Duty',
        ),
        migrations.AlterModelOptions(
            name='duty',
            options={'verbose_name_plural': 'Duties'},
        ),
        migrations.RemoveField(
            model_name='position',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='position',
            name='duties',
            field=models.ManyToManyField(blank=True, related_name='position_duties', to='_work.duty'),
        ),
        migrations.AddField(
            model_name='position',
            name='end',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='position',
            name='start',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='end',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
