# Generated by Django 4.0.3 on 2022-03-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_work', '0002_rename_responsibility_duty_alter_duty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='label',
            field=models.CharField(max_length=18),
        ),
    ]
