# Generated by Django 4.0.3 on 2022-03-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_work', '0002_alter_entry_options_alter_responsibility_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='element_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='element_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='element_id',
            field=models.IntegerField(default=0),
        ),
    ]
