# Generated by Django 4.0.3 on 2022-03-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_work', '0003_entry_element_id_position_element_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='label',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
    ]
