# Generated by Django 4.0.3 on 2022-03-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=36)),
                ('provider', models.CharField(max_length=36)),
                ('start', models.CharField(max_length=18)),
                ('end', models.CharField(max_length=18)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='group_courses', to='_education.course'),
        ),
    ]
