# Generated by Django 4.0.3 on 2022-03-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_education', '0002_course_group_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='element_id',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
